/* Placeholder data for VidimoSe.hr landing page */

export type InvitationTemplate = {
  id: string
  theme: string
  /** Ilustracija teme (ispod naslova u sekciji Kreiraj pozivnicu). */
  image: string
  /** Puna slika pozivnice za lightbox popup. */
  fullImage: string
  childName: string
  age: string
  date: string
  venue: string
  address: string
  time: string
}

export type VenuePackage = {
  name: string
  price: number
  minChildren: number
  includes: string[]
}

export type Venue = {
  id: string
  slug: string
  name: string
  city: string
  address: string
  phone: string
  rating: number
  reviewCount: number
  pricePerChild: number
  ageRange: string
  ageMin: number
  ageMax: number
  maxChildren: number
  description: string
  amenities: string[]
  coverPhoto: string
  photos: string[]
  packages: VenuePackage[]
}

export type Testimonial = {
  quote: string
  name: string
  childAge: string
  city: string
  monogram: string
}

export type FAQItem = {
  question: string
  answer: string
}

export const invitationTemplates: InvitationTemplate[] = [
  {
    id: 'decko',
    theme: 'Dečko',
    image: '/decko.webp',
    fullImage: '/decko.webp',
    childName: 'Noa',
    age: '6',
    date: 'Subota, 7. lipnja',
    venue: 'Šumska Avantura',
    address: 'Maksimirska 12, Zagreb',
    time: '16:00 — 18:00',
  },
  {
    id: 'safari',
    theme: 'Safari',
    image: '/safari.png',
    fullImage: '/safari.png',
    childName: 'Luka',
    age: '5',
    date: 'Subota, 21. lipnja',
    venue: 'Džungla Park',
    address: 'Vukovarska 47, Zagreb',
    time: '16:00 — 18:00',
  },
  {
    id: 'unicorn',
    theme: 'Jednorog',
    image: '/unicorns.png',
    fullImage: '/unicorns.png',
    childName: 'Mia',
    age: '4',
    date: 'Nedjelja, 8. lipnja',
    venue: 'Čarobni Kutak',
    address: 'Ilica 220, Zagreb',
    time: '15:00 — 17:30',
  },
  {
    id: 'svemir',
    theme: 'Svemir',
    image: '/space.png',
    fullImage: '/space.png',
    childName: 'Filip',
    age: '7',
    date: 'Subota, 14. lipnja',
    venue: 'Rocket Room',
    address: 'Avenija Dubrovnik 12, Zagreb',
    time: '14:00 — 16:30',
  },
  {
    id: 'princess',
    theme: 'Princeza',
    image: '/princess.png',
    fullImage: '/princess.png',
    childName: 'Petra',
    age: '6',
    date: 'Subota, 28. lipnja',
    venue: 'Arena Junior',
    address: 'Kneza Branimira 88, Split',
    time: '10:00 — 12:30',
  },
]

export const venues: Venue[] = [
  {
    id: 'habyland',
    slug: 'habyland-zagreb',
    name: 'Habyland',
    city: 'Zagreb',
    address: 'Avenija Dubrovnik 15 (Velesajam, Paviljon 25), 10020 Zagreb',
    phone: '+385 1 6187 715',
    rating: 4.7,
    reviewCount: 180,
    pricePerChild: 11,
    ageRange: '0–12',
    ageMin: 0,
    ageMax: 12,
    maxChildren: 30,
    description: 'Jedna od najvećih igraonica u Zagrebu s 1.250 m² prostora — trampolini, napuhanci, tobogani, labirint, arkadne igre i tematski kutak za bebe. TÜV certificirana oprema i profesionalni animatori za svaki paket.',
    amenities: ['Parking', 'Ugostiteljstvo', 'Animatori', 'Trampolini', 'Klima', 'Video nadzor', 'TÜV certifikat'],
    coverPhoto: 'https://habyland.com/wp-content/uploads/2024/12/DJECJA-IGRAONICA-HABYLAND-3-scaled-1920x1200.jpg',
    photos: [
      'https://habyland.com/wp-content/uploads/2024/12/habyland-igraonica-i-rodendani-za-djecu-zagreb-8-1920x1200.jpg',
      'https://habyland.com/wp-content/uploads/2024/12/habyland-igraonica-i-rodendani-za-djecu-zagreb-17-1920x1200.jpg',
      'https://habyland.com/wp-content/uploads/2024/12/habyland-igraonica-i-rodendani-za-djecu-zagreb-13-1920x1200.jpg',
      'https://habyland.com/wp-content/uploads/2024/12/habyland-igraonica-i-rodendani-za-djecu-zagreb-33-1920x1200.jpg',
    ],
    packages: [
      { name: 'Speedy', price: 170, minChildren: 15, includes: ['2h igranje', 'animatori', 'dekoracija', 'sokovi i snacks'] },
      { name: 'Fun Fun Funny', price: 230, minChildren: 20, includes: ['2.5h igranje', 'animatori', 'pizza', 'sokovi', 'dekoracija'] },
      { name: 'Habyland Magic', price: 350, minChildren: 25, includes: ['3h igranje', 'puni catering', 'torta', '2 animatora', 'foto rekviziti', 'dekoracija'] },
    ],
  },
  {
    id: 'play2day',
    slug: 'play2day-zagreb',
    name: 'Play2day',
    city: 'Zagreb',
    address: 'Zagrebački Velesajam, Avenija Dubrovnik 15, Paviljon 33, 10020 Zagreb',
    phone: '+385 91 563 1715',
    rating: 4.6,
    reviewCount: 72,
    pricePerChild: 17,
    ageRange: '4–12',
    ageMin: 4,
    ageMax: 12,
    maxChildren: 25,
    description:
      'Kineziološki tim s više od 10 godina iskustva na prostoru većem od 1.800 m² — sportski rođendani, sportaonica s 60+ igara i do 15 sportova kroz zabavu i kretanje, ljetni kampovi i obiteljski izleti. U istom kompleksu Velesajma kao ostale igraonice uz Aveniju Dubrovnik.',
    amenities: ['Parking', 'Animatori', 'Trampolini', 'Air Hockey', 'Labirinti', 'Klima', 'Ugostiteljstvo'],
    coverPhoto: 'https://picsum.photos/seed/play2day-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/play2day-1/1200/750',
      'https://picsum.photos/seed/play2day-2/1200/750',
      'https://picsum.photos/seed/play2day-3/1200/750',
      'https://picsum.photos/seed/play2day-4/1200/750',
    ],
    packages: [
      { name: 'Sportski rođendan', price: 220, minChildren: 15, includes: ['2h programa', 'kineziolozi / animatori', 'sportski sadržaj', 'osvježenje', 'rezervacija prostora'] },
      { name: 'Sportaonica party', price: 260, minChildren: 15, includes: ['2h', 'tematske i sportske igre', 'animatori', 'osvježenje', 'dekoracija'] },
      { name: 'Kamp / izlet (info)', price: 290, minChildren: 12, includes: ['Kontaktiraj Play2day za kampove i izlete', 'program na otvorenom ili u dvorani', 'grupa po dogovoru'] },
    ],
  },
  {
    id: 'igrandia',
    slug: 'igrandia-zagreb',
    name: 'iGRANDiA',
    city: 'Zagreb',
    address: 'Ulica Velimira Škorpika 11, 10090 Zagreb (Family Mall, 1. kat)',
    phone: '+385 1 353 5785',
    rating: 4.6,
    reviewCount: 1401,
    pricePerChild: 20,
    ageRange: '1.5–12',
    ageMin: 1,
    ageMax: 12,
    maxChildren: 35,
    description: '3.500 m² igraonice u Family Mallu — mega napuhanac "Kraljevstvo", 5-katna džungla s tobogānima, Sky Rider zipline, Minecraft poligon, Vodeni svijet i 10+ tematskih soba za roleplay. Besplatan parking ispred.',
    amenities: ['Parking', 'Trampolini', 'Tematske sobe', 'Animatori', 'Torta po narudžbi', 'Kafić za roditelje', 'Klima'],
    coverPhoto: 'https://igrandia.hr/wp-content/uploads/2025/07/02-Igrandia-napuhanac-e1753173406817.jpg',
    photos: [
      'https://igrandia.hr/wp-content/uploads/2024/04/07-Igrandia-bazen-s-plavim-loptama-e1753173573515.webp',
      'https://igrandia.hr/wp-content/uploads/2025/07/01-Igrandia-Minecraft-poligon-e1753173892533.webp',
      'https://igrandia.hr/wp-content/uploads/2025/12/Vodeni_svijet-465x465.jpg',
      'https://igrandia.hr/wp-content/uploads/2025/11/Pjescanik_s_mramornim_kuglicama-465x465.jpg',
    ],
    packages: [
      { name: 'Super Cool', price: 200, minChildren: 10, includes: ['2h igranje', 'animatori', 'dekoracija', 'napitak za djecu'] },
      { name: 'Kids Escape Room', price: 230, minChildren: 10, includes: ['Escape room avantura', 'igranje', 'animatori', 'catering'] },
      { name: 'Minecraft Party', price: 320, minChildren: 10, includes: ['Tematska Minecraft soba', '2.5h', 'puni catering', 'animator', 'torta po izboru'] },
    ],
  },
  {
    id: 'ententini',
    slug: 'ententini-zagreb',
    name: 'EnTenTini',
    city: 'Zagreb',
    address: 'Koledinečka ulica 5, 10000 Zagreb (Dubrava)',
    phone: '01 2912 347',
    rating: 4.6,
    reviewCount: 80,
    pricePerChild: 9,
    ageRange: '3–10',
    ageMin: 3,
    ageMax: 10,
    maxChildren: 20,
    description: 'Ugodna igraonica u Dubravi s obstacle coursem, toboganom i odvojenim prostorom za roditelje s kavom. Dva animatora uključena u svaki paket, sladoledna torta i fotografija. Odlično za mlađe predškolce.',
    amenities: ['Animatori', 'Kafić za roditelje', 'Torta po narudžbi', 'Klima', 'Svlačionice'],
    coverPhoto: 'https://ententini.hr/wp-content/uploads/2016/02/slide2-1.jpg',
    photos: [
      'https://ententini.hr/wp-content/uploads/2016/02/slide3-1.jpg',
      'https://ententini.hr/wp-content/uploads/2016/02/slide4-1.jpg',
      'https://ententini.hr/wp-content/uploads/2016/02/slide5-1.jpg',
      'https://ententini.hr/wp-content/uploads/2016/02/slide2-1.jpg',
    ],
    packages: [
      { name: 'Cool Ročkas', price: 170, minChildren: 20, includes: ['2h igranje', '2 animatora', 'sladoledna torta', 'snacks', 'fotografija', 'dekoracija'] },
      { name: 'Super Cool Ročkas', price: 200, minChildren: 20, includes: ['2h igranje', '2 animatora', 'torta', 'pizze i kolači', 'dekoracija', 'poklon vrećice'] },
      { name: 'Naj Naj Ročkas', price: 260, minChildren: 20, includes: ['2h igranje', '2 animatora', 'torta', 'catering', '4 add-ona po izboru (disco, bounce castle...)'] },
    ],
  },
  {
    id: 'time2play',
    slug: 'time2play-zagreb',
    name: 'Time2Play',
    city: 'Zagreb',
    address: 'Lanište 1e, 10020 Zagreb (Novi Zagreb)',
    phone: '095 525 2369',
    rating: 4.5,
    reviewCount: 60,
    pricePerChild: 16,
    ageRange: '3–12',
    ageMin: 3,
    ageMax: 12,
    maxChildren: 20,
    description: 'Moderna igraonica u Novom Zagrebu s PS4, VR sustavima, sportskom zonom i kreativnim radionicama. Svaki paket all-inclusive — torta, dekoracija i animatori su uvijek uključeni. WhatsApp rezervacije.',
    amenities: ['Animatori', 'Torta po narudžbi', 'PS4 i VR zone', 'Parking', 'Klima', 'Svlačionice'],
    coverPhoto: 'https://time2play.hr/images/made/images/uploads/IMG_6290_1200_800_90_s_c1.JPG',
    photos: [
      'https://time2play.hr/images/made/images/uploads/poc-igraonica_1200_800_90_s_c1.jpg',
      'https://time2play.hr/images/made/images/uploads/P2000457_1200_800_90_s_c1.JPG',
      'https://time2play.hr/images/made/images/uploads/P1990803_1200_800_90_s_c1.JPG',
      'https://time2play.hr/images/made/images/uploads/poc-igraonica_800_600_80_s_c1.jpg',
    ],
    packages: [
      { name: 'Time2Start', price: 240, minChildren: 15, includes: ['2h igranje', 'animatori', 'torta', 'dekoracija', 'napitak'] },
      { name: 'Time2Dance', price: 270, minChildren: 15, includes: ['Disco/ples tema', '2h igranje', 'animatori', 'torta', 'dekoracija'] },
      { name: 'Time2Bday', price: 280, minChildren: 15, includes: ['Tematska proslava', 'VR zona', '2h igranje', 'puni catering', 'animator'] },
    ],
  },
  {
    id: 'fijubriju',
    slug: 'fijubriju-zagreb',
    name: 'Fiju Briju',
    city: 'Zagreb',
    address: 'Ulica Hrvatskog proljeća 24, 10000 Zagreb (Dubrava)',
    phone: '091 30 777 11',
    rating: 4.7,
    reviewCount: 82,
    pricePerChild: 9,
    ageRange: '4–12',
    ageMin: 4,
    ageMax: 12,
    maxChildren: 20,
    description: 'Moderni dječji klub u Dubravi s profesionalnim osobljem, alarmnim sustavom i video nadzorom. Karaoke, bubble i fog machine, light show — i mobilna animacija za vanjska slavlja. Nude i "Fiju Briju To Go".',
    amenities: ['Animatori', 'Torta po narudžbi', 'Karaoke', 'Bubble/Fog Machine', 'Klima', 'Video nadzor', 'Wi-Fi'],
    coverPhoto: 'https://fijubriju.hr/wp-content/uploads/2020/05/Fiju-Briju1.png',
    photos: [
      'https://picsum.photos/seed/fiju1/800/500',
      'https://picsum.photos/seed/fiju2/800/500',
      'https://picsum.photos/seed/fiju3/800/500',
      'https://picsum.photos/seed/fiju4/800/500',
    ],
    packages: [
      { name: 'Tulum', price: 170, minChildren: 20, includes: ['2h igranje', '2 animatora', 'sokovi i snacks', 'dekoracija', 'karaoke', 'foto na USB'] },
      { name: 'Tulum+', price: 190, minChildren: 20, includes: ['2h igranje', '2 animatora', 'sokovi i snacks', 'dekoracija', 'karaoke', 'Ledo torta', 'foto na USB'] },
      { name: 'Tulum Maxi', price: 220, minChildren: 20, includes: ['2h igranje', '2 animatora', 'pizza', 'Ledo torta', 'dekoracija', 'karaoke', 'foto na USB'] },
    ],
  },
  {
    id: 'jumbo',
    slug: 'jumbo-igraonica-zagreb',
    name: 'Igraonica Jumbo',
    city: 'Zagreb',
    address: 'Zagrebačka avenija 94, 10010 Zagreb (Špansko)',
    phone: '098 138 0498',
    rating: 4.5,
    reviewCount: 90,
    pricePerChild: 17,
    ageRange: '5–12',
    ageMin: 5,
    ageMax: 12,
    maxChildren: 20,
    description: '750 m² igraonice u Španskom s velikim labirintom, 4 tobogana, trampolinima, Air Hockeyem, laserskim pištoljima i disco/foam partijima. Dvije privatne animacijske dvorane od 50 m². Isključivo rezervacije za rođendane.',
    amenities: ['Parking', 'Ugostiteljstvo', 'Animatori', 'Trampolini', 'Air Hockey', 'Labirinti', 'Klima'],
    coverPhoto: 'https://www.igraonice.hr/media/images/modules/igraonice/galerije/original/djecja-igraonica-jumbo-zajednicka-dvorana-napuhanac.jpg',
    photos: [
      'https://www.igraonice.hr/media/images/modules/igraonice/galerije/original/djecja-igraonica-jumbo-zajednicka-dvorana-tobogani.jpg',
      'https://www.igraonice.hr/media/images/modules/igraonice/galerije/original/djecja-igraonica-jumbo-zajednicka-dvorana-bazen-s-lopticama.jpg',
      'https://www.igraonice.hr/media/images/modules/igraonice/galerije/original/djecja-igraonica-jumbo-animacijske-dvorane-desna-1.jpg',
      'https://www.igraonice.hr/media/images/modules/igraonice/galerije/original/djecja-igraonica-jumbo-animacijske-dvorane-lijeva-1.jpg',
    ],
    packages: [
      { name: 'Standard 2h', price: 350, minChildren: 20, includes: ['2h igranje', '2 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'face painting', 'foto na USB', 'poklon za slavlje'] },
      { name: 'Extended 3h', price: 390, minChildren: 20, includes: ['3h igranje (pon–pet)', '2 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'face painting', 'foto na USB', 'poklon za slavlje'] },
      { name: 'Extra animator', price: 420, minChildren: 20, includes: ['2h igranje', '3 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'face painting', 'foto na USB', 'poklon za slavlje'] },
    ],
  },
  {
    id: 'jungleplay2',
    slug: 'jungle-play-2-zagreb',
    name: 'Jungle Play 2',
    city: 'Zagreb',
    address: 'Zagrebačka avenija 94, 10010 Zagreb (Špansko)',
    phone: '098 138 0498',
    rating: 4.6,
    reviewCount: 75,
    pricePerChild: 17,
    ageRange: '4–12',
    ageMin: 4,
    ageMax: 12,
    maxChildren: 20,
    description: '750 m² prostora u Španskom s dva velika labirinta, 6 tobogana u bazene s lopticama, trampolinima i Air Hockeyem. Isti kompleks kao Igraonica Jumbo — mlađa djeca (od 4 god.) dobrodošla. Rezervacije 3–4 tjedna unaprijed.',
    amenities: ['Parking', 'Ugostiteljstvo', 'Animatori', 'Trampolini', 'Air Hockey', 'Labirinti', 'Klima'],
    coverPhoto: 'https://www.igraonice.hr/media/images/modules/igraonice/igraonica/original/djecija-igraonica-jungle-play-2.jpg',
    photos: [
      'https://www.igraonice.hr/media/images/modules/igraonice/galerije/original/dvorana-3-kids-club-jungle-slika-1.jpg',
      'https://www.igraonice.hr/media/images/modules/igraonice/galerije/original/dvorana-jungle-play-2-slika-10.jpg',
      'https://www.igraonice.hr/media/images/modules/igraonice/galerije/original/dvorana-jungle-play-2-slika-11.jpg',
      'https://www.igraonice.hr/media/images/modules/igraonice/galerije/original/dvorana-jungle-play-2-slika-12.jpg',
    ],
    packages: [
      { name: 'Standard 2h', price: 350, minChildren: 20, includes: ['2h igranje', '2 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'face painting', 'foto na USB', 'poklon za slavlje'] },
      { name: 'Extra animator', price: 380, minChildren: 20, includes: ['2h igranje', '3 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'face painting', 'foto na USB', 'poklon za slavlje'] },
      { name: 'Extra torta', price: 370, minChildren: 20, includes: ['2h igranje', '2 animatora', 'pizza', '2 Ledo torte', 'pozivnice', 'face painting', 'foto na USB', 'poklon za slavlje'] },
    ],
  },
  {
    id: 'plavisvijet',
    slug: 'plavi-svijet-zagreb',
    name: 'Plavi Svijet',
    city: 'Zagreb',
    address: 'Ulica Ede Murtića 2B, 10020 Zagreb (Središće)',
    phone: '099 868 6260',
    rating: 4.5,
    reviewCount: 55,
    pricePerChild: 23,
    ageRange: '0–12',
    ageMin: 0,
    ageMax: 12,
    maxChildren: 30,
    description: 'Kreativna igraonica kraj Muzeja suvremene umjetnosti s edukativnim igračkama, obstacle courseom i ekskluzivnim rezerviranjem cijelog prostora za goste. Poseban Baby paket za najmlađe i Teen paket od 10 godina.',
    amenities: ['Kreativne radionice', 'Animatori', 'Ekskluzivni prostor', 'Klima', 'WC za bebe', 'Kuhinja za bebe'],
    coverPhoto: 'https://plavisvijet.com/wp-content/uploads/2024/02/dan-u-igraonici-7.jpg',
    photos: [
      'https://plavisvijet.com/wp-content/uploads/2024/02/dan-u-igraonici-9.jpg',
      'https://plavisvijet.com/wp-content/uploads/2024/02/dan-u-igraonici-6.jpg',
      'https://plavisvijet.com/wp-content/uploads/2024/02/dan-u-igraonici-4.jpg',
      'https://plavisvijet.com/wp-content/uploads/2024/02/dan-u-igraonici-8.jpg',
    ],
    packages: [
      { name: 'Mini', price: 230, minChildren: 10, includes: ['2h igranje', 'animator', 'kreativne radionice', 'ekskluzivan prostor'] },
      { name: 'Midi', price: 270, minChildren: 20, includes: ['2h igranje', 'animator', 'kreativne radionice', 'ekskluzivan prostor'] },
      { name: 'Baby / Teen', price: 310, minChildren: 15, includes: ['Specijaliziran format po dobi', '2h', 'animator', 'ekskluzivan prostor', 'poklon setovi'] },
    ],
  },
  {
    id: 'sarenibalon',
    slug: 'sareni-balon-zagreb',
    name: 'Šareni Balon',
    city: 'Zagreb',
    address: 'Rudeška cesta 169a, POINT Shopping Center, 10000 Zagreb',
    phone: '+385 1 484 4299',
    rating: 4.5,
    reviewCount: 95,
    pricePerChild: 10,
    ageRange: '1–12',
    ageMin: 1,
    ageMax: 12,
    maxChildren: 30,
    description: 'Igraonica u POINT Shopping Centru s labirintom, toboganima, trampolinima, zip lineom, zidovima za penjanje i posebnim kutkom za bebe. Svaki paket uključuje animatore, dekoraciju, snacks i foto CD.',
    amenities: ['Parking', 'Animatori', 'Trampolini', 'Klima', 'Labirinti', 'Kafić za roditelje'],
    coverPhoto: 'https://sarenibalon.com/wp-content/uploads/2018/06/1200x500-1.jpg',
    photos: [
      'https://sarenibalon.com/wp-content/uploads/2018/06/Untitled.jpg',
      'https://sarenibalon.com/wp-content/uploads/2018/06/Untitled1.jpg',
      'https://sarenibalon.com/wp-content/uploads/2018/06/Untitled3.jpg',
      'https://sarenibalon.com/wp-content/uploads/2018/06/Untitled4.jpg',
    ],
    packages: [
      { name: 'Standard Party', price: 170, minChildren: 15, includes: ['2h igranje', 'animatori', 'dekoracija', 'disk party', 'snacks i sokovi', 'foto CD'] },
      { name: 'Kreativne radionice', price: 200, minChildren: 15, includes: ['2h igranje', 'animatori', 'kreativna radionica', 'dekoracija', 'snacks i sokovi', 'foto CD'] },
      { name: 'Premium Party', price: 250, minChildren: 20, includes: ['2.5h igranje', '2 animatora', 'puni catering', 'dekoracija', 'foto CD', 'poklon vrećice'] },
    ],
  },
  {
    id: 'minipolis',
    slug: 'minipolis-zagreb',
    name: 'MiniPolis',
    city: 'Zagreb',
    address: 'Ljubljanska avenija 2b, Z-centar, 10000 Zagreb',
    phone: '+385 1 209 9259',
    rating: 4.7,
    reviewCount: 320,
    pricePerChild: 19,
    ageRange: '3–12',
    ageMin: 3,
    ageMax: 12,
    maxChildren: 40,
    description: 'Minijaturni grad na 2.000 m² s 40+ tematskih kućica, karting stazom, kafićem, vatrogasnom stanicom, bolnicom i supermarketom. Djeca igraju odrasle uloge uz animatore. Smještaj u Z-centru s besplatnim parkiranjem.',
    amenities: ['Parking', 'Animatori', 'Tematske sobe', 'Klima', 'Kafić za roditelje', 'Karting staza', 'Wi-Fi'],
    coverPhoto: 'https://minipolis.b-cdn.net/wp-content/uploads/2026/04/DSC03766-1024x683.jpg',
    photos: [
      'https://minipolis.b-cdn.net/wp-content/uploads/2025/01/MiniPolis_Pozadina.webp',
      'https://minipolis.b-cdn.net/wp-content/uploads/2022/08/bg-03-free-img.png',
      'https://minipolis.b-cdn.net/wp-content/uploads/2021/04/background-2.png',
      'https://minipolis.b-cdn.net/wp-content/uploads/2021/04/footer-top-mipo.webp',
    ],
    packages: [
      { name: 'MiniPolis PROMO', price: 190, minChildren: 10, includes: ['2h igranje', 'animatori', 'dekoracija', 'osvježenje', 'pon–čet'] },
      { name: 'Veterinary Adventure', price: 290, minChildren: 10, includes: ['2.5h igranje', 'animatori', 'tematska avantura', 'dekoracija', 'osvježenje'] },
      { name: 'World of Fun', price: 360, minChildren: 10, includes: ['2.5h igranje', 'animatori', 'dekoracija', 'pokloni za goste', 'puno osvježenje'] },
    ],
  },
  {
    id: 'djecjiescaperoom',
    slug: 'djecji-escape-room-zagreb',
    name: 'Dječji Escape Room',
    city: 'Zagreb',
    address: 'Avenija Dubrovnik 15, paviljon 10, 10020 Zagreb',
    phone: '+385 98 190 0874',
    rating: 4.8,
    reviewCount: 140,
    pricePerChild: 22,
    ageRange: '8–14',
    ageMin: 8,
    ageMax: 14,
    maxChildren: 35,
    description: 'Jedini dječji escape room u Zagrebu s tematskim sobama za bijeg — pireti, detektivi, čarolija. Svaki paket all-inclusive: soba, game master, prostor za slavlje, torta, dekoracija i snacks. Bez depozita, besplatan parking.',
    amenities: ['Parking', 'Escape room', 'Animatori', 'Torta po narudžbi', 'Klima'],
    coverPhoto: 'https://djecjiescaperoom.eu/wp-content/uploads/2024/09/WhatsApp-Image-2024-09-03-at-22.06.30.jpeg',
    photos: [
      'https://djecjiescaperoom.eu/wp-content/uploads/2020/09/Djecji-rodendan-5.jpeg',
      'https://djecjiescaperoom.eu/wp-content/uploads/2024/03/98bf3544-cc59-43cb-a6d8-71e0ca311212.jpg',
      'https://djecjiescaperoom.eu/wp-content/uploads/2024/09/WhatsApp-Image-2024-09-03-at-22.06.33-1.jpeg',
      'https://djecjiescaperoom.eu/wp-content/uploads/2024/09/WhatsApp-Image-2024-09-03-at-22.06.33-2.jpeg',
    ],
    packages: [
      { name: 'Mala grupa', price: 250, minChildren: 2, includes: ['2h', '1 tematska soba', 'game master', 'prostor za slavlje', 'torta', 'snacks', 'foto na WhatsApp'] },
      { name: 'Srednja grupa', price: 350, minChildren: 10, includes: ['2h', '2 tematske sobe', '2 game mastera', 'prostor za slavlje', 'torta', 'snacks', 'foto na WhatsApp'] },
      { name: 'Velika grupa', price: 450, minChildren: 19, includes: ['2h', '3 tematske sobe', '2+ game mastera', 'prostor za slavlje', 'torta', 'snacks', 'foto na WhatsApp'] },
    ],
  },
  {
    id: 'familypark',
    slug: 'family-park-jablanovec',
    name: 'Family Park',
    city: 'Jablanovec',
    address: 'Westgate Shopping City, Zaprešićka 2, 10290 Jablanovec',
    phone: '099 222 0300',
    rating: 4.5,
    reviewCount: 210,
    pricePerChild: 13,
    ageRange: '0–12',
    ageMin: 0,
    ageMax: 12,
    maxChildren: 30,
    description: 'Velika igraonica u Westgate Shopping Cityju s odvojenim kutkom za bebe (0–5) i velikom dvoranom za stariju djecu (4–12), karting stazom Mini Cars, VR simulatorom i restoran s pogledom na igraonicu.',
    amenities: ['Parking', 'Restoran', 'Animatori', 'Klima', 'Wi-Fi', 'VR simulator', 'Mini Cars'],
    coverPhoto: 'https://familypark.hr/wp-content/uploads/2020/01/bg4.jpg',
    photos: [
      'https://familypark.hr/wp-content/uploads/2023/10/20230821_134936-scaled.jpg',
      'https://familypark.hr/wp-content/uploads/2023/10/v8-scaled-e1698597914799.jpg',
      'https://familypark.hr/wp-content/uploads/2020/01/tica-bg.jpg',
      'https://familypark.hr/wp-content/uploads/2020/02/VL.jpg',
    ],
    packages: [
      { name: 'Family Paket Baby', price: 125, minChildren: 10, includes: ['2h igranje (0–5 god.)', 'asistent', 'prirodni sok', 'snacks', 'pozivnice', 'čišćenje'] },
      { name: 'Family Paket Standard', price: 145, minChildren: 10, includes: ['2h igranje (4–12 god.)', 'animatori', 'sok', 'snacks', 'pozivnice', 'digitalne fotografije'] },
      { name: 'Weekday Special', price: 145, minChildren: 10, includes: ['3h igranje pon–čet', 'animatori', 'sok', 'snacks', 'pozivnice', 'digitalne fotografije', '15% popust'] },
    ],
  },
  {
    id: 'jogica',
    slug: 'jogica-zagreb',
    name: 'Jogica',
    city: 'Zagreb',
    address: 'Vojakovačka ulica 39, Gajevo, 10000 Zagreb',
    phone: '091 514 1926',
    rating: 4.6,
    reviewCount: 65,
    pricePerChild: 13,
    ageRange: '1–10',
    ageMin: 1,
    ageMax: 10,
    maxChildren: 20,
    description: 'Moderan dječji klub u Gajevu s parkingom na dvije ulice. Sport, disco, princeze ili safari — tematske proslave s DJ opremom, face paintingom i maskotama na poziv. Detaljan fotoalbum uz svaki paket.',
    amenities: ['Parking', 'Animatori', 'Torta po narudžbi', 'DJ oprema', 'Face painting', 'Klima'],
    coverPhoto: 'https://jogica.com.hr/wp-content/uploads/2026/04/20260216_175918.jpg',
    photos: [
      'https://jogica.com.hr/wp-content/uploads/2026/04/20260216_183628.jpg',
      'https://jogica.com.hr/wp-content/uploads/2026/04/20260310_183957.jpg',
      'https://jogica.com.hr/wp-content/uploads/2026/04/20260401_180821.jpg',
      'https://jogica.com.hr/wp-content/uploads/2026/04/20260401_182017.jpg',
    ],
    packages: [
      { name: 'Basic Party', price: 250, minChildren: 15, includes: ['2h igranje', '2 animatora', 'pizza', 'torta', 'snacks', 'sokovi', 'fotografije'] },
      { name: 'Sport / Disco Party', price: 270, minChildren: 15, includes: ['2h igranje', 'tematski program', 'DJ oprema / sportske igre', 'pizza', 'torta', 'snacks'] },
      { name: 'Themed Party', price: 330, minChildren: 15, includes: ['2h igranje', 'tematska dekoracija', 'animatori', 'pizza', 'torta', 'snacks', 'face painting'] },
    ],
  },
  {
    id: 'lollipop',
    slug: 'lollipop-zagreb',
    name: 'Lollipop',
    city: 'Zagreb',
    address: 'Laška ulica 12, 10000 Zagreb (Gornja Dubrava)',
    phone: '095 197 4489',
    rating: 4.7,
    reviewCount: 110,
    pricePerChild: 7,
    ageRange: '1–14',
    ageMin: 1,
    ageMax: 14,
    maxChildren: 25,
    description: 'Tematska igraonica i rođendaonica u Gornjoj Dubravi s 2 animatora pedagoške struke i kutkom za roditelje. 10+ tema (Frozen, Hogwarts, Barbie, Vile, James Bond, Super junaci, Jedi trening, Lolly Glam) plus Baby i Pidžama party. Neograničene grickalice i pića te CD s fotografijama uvijek uključeni.',
    amenities: ['Animatori', 'Tematske sobe', 'Torta po narudžbi', 'Kafić za roditelje', 'Kreativne radionice', 'Foto kutić', 'Klima'],
    coverPhoto: 'https://picsum.photos/seed/lollipop-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/lollipop-1/1200/750',
      'https://picsum.photos/seed/lollipop-2/1200/750',
      'https://picsum.photos/seed/lollipop-3/1200/750',
      'https://picsum.photos/seed/lollipop-4/1200/750',
    ],
    packages: [
      { name: 'Lolly Baby / Pidžama', price: 135, minChildren: 20, includes: ['2h igranje', '2 animatora', 'soft play / pidžama party', 'grickalice i pića', 'dekoracija', 'foto CD'] },
      { name: 'Lolly Basic', price: 150, minChildren: 20, includes: ['2h igranje', '2 animatora', 'dekoracija', 'neograničene grickalice', 'kutak za roditelje', 'foto CD'] },
      { name: 'Tematski paket (Frozen, Hogwarts, Barbie…)', price: 175, minChildren: 20, includes: ['2h igranje', '2 animatora', 'tematska dekoracija', 'kostimi i rekviziti', 'grickalice i pića', 'foto CD'] },
    ],
  },
  {
    id: 'carpyland',
    slug: 'carpyland-zagreb',
    name: 'Carpyland',
    city: 'Zagreb',
    address: 'Ulica Vice Vukova 6, Arena Centar, 10020 Zagreb',
    phone: '+385 1 5801 940',
    rating: 4.4,
    reviewCount: 240,
    pricePerChild: 14,
    ageRange: '1–12',
    ageMin: 1,
    ageMax: 12,
    maxChildren: 25,
    description: 'Velika igraonica modernog dizajna u srcu Arena Centra s edukativnim igračkama, kostimiranim animatorima i vlastitom maskotom Carpy. Edukativno-zabavni programi (Tajne šifre i pisma, Ledeno doba, Čarobni svijet magneta, Znanost o bojama) plus modeliranje balona, face painting i ples. Otvoreno svaki dan 08–22.',
    amenities: ['Parking', 'Animatori', 'Tematske sobe', 'Foto rekviziti', 'Face painting', 'Klima', 'Kreativne radionice'],
    coverPhoto: 'https://picsum.photos/seed/carpyland-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/carpyland-1/1200/750',
      'https://picsum.photos/seed/carpyland-2/1200/750',
      'https://picsum.photos/seed/carpyland-3/1200/750',
      'https://picsum.photos/seed/carpyland-4/1200/750',
    ],
    packages: [
      { name: 'Standard animacijski', price: 220, minChildren: 12, includes: ['2h igranje', 'animatori', 'modeliranje balona', 'face painting', 'dekoracija', 'osvježenje'] },
      { name: 'Edu-zabavni', price: 280, minChildren: 12, includes: ['2.5h igranje', 'tematski program (npr. Ledeno doba)', 'pokusi i radionica', 'animatori', 'osvježenje'] },
      { name: 'Maskota Carpy', price: 320, minChildren: 15, includes: ['2.5h igranje', 'maskota Carpy', 'kostimirani animatori', 'tematska dekoracija', 'puni catering'] },
    ],
  },
  {
    id: 'kidsjungle',
    slug: 'kids-jungle-cco-zagreb',
    name: "Kid's Jungle",
    city: 'Zagreb',
    address: 'City Center one West, Jankomir 33, 10090 Zagreb',
    phone: '+385 91 244 2762',
    rating: 4.5,
    reviewCount: 320,
    pricePerChild: 20,
    ageRange: '4–11',
    ageMin: 4,
    ageMax: 11,
    maxChildren: 20,
    description: 'Sigurnosni standardi po europskim normama (prva certificirana igraonica u Hrvatskoj), animatori s tečajem prve pomoći i edukativne radionice svaki tjedan. All-inclusive Jungle Party s maskotom tigrićem Tobijem, tematske teme (Princeze, Gusari) i 10% popust za članove Jungle Cluba.',
    amenities: ['Parking', 'Animatori', 'Torta po narudžbi', 'Kreativne radionice', 'Tematske sobe', 'Klima', 'Video nadzor'],
    coverPhoto: 'https://picsum.photos/seed/kidsjungle-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/kidsjungle-1/1200/750',
      'https://picsum.photos/seed/kidsjungle-2/1200/750',
      'https://picsum.photos/seed/kidsjungle-3/1200/750',
      'https://picsum.photos/seed/kidsjungle-4/1200/750',
    ],
    packages: [
      { name: 'Jungle Party Basic', price: 203, minChildren: 10, includes: ['2h igranje', 'animatori', 'maskota Tobi', 'Ledo torta', 'pizza i fornete', 'sokovi', 'tiskane pozivnice', 'pokloni za goste'] },
      { name: 'Princezin / Gusarski Party', price: 240, minChildren: 10, includes: ['2h igranje', 'tematska dekoracija', 'kostimi', 'maskota Tobi', 'torta', 'catering', 'pokloni'] },
      { name: 'Premium s radionicom', price: 280, minChildren: 12, includes: ['2.5h igranje', 'znanstvena radionica ili face painting', 'animatori', 'torta', 'puni catering', 'pokloni'] },
    ],
  },
  {
    id: 'cirkus',
    slug: 'cirkus-zagreb',
    name: 'Igraonica Cirkus',
    city: 'Zagreb',
    address: 'Branimirova 29, Branimir centar, 10000 Zagreb',
    phone: '098 138 0498',
    rating: 4.6,
    reviewCount: 95,
    pricePerChild: 17,
    ageRange: '3–12',
    ageMin: 3,
    ageMax: 12,
    maxChildren: 25,
    description: '380 m² igraonice u centru grada, podijeljene u 3 dvorane (Kid\'s Club Cirkus 180 m² ima labirint s 2 tobogana, 2 bazena s lopticama, trampolin i PlayStation). Svaka grupa ima svoj ulaz i animatore — bez miješanja s drugom djecom. Dio Jumbo Loyalty programa.',
    amenities: ['Animatori', 'Trampolini', 'Air Hockey', 'Labirinti', 'PS4 i VR zone', 'Foto kutić', 'Klima'],
    coverPhoto: 'https://picsum.photos/seed/cirkus-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/cirkus-1/1200/750',
      'https://picsum.photos/seed/cirkus-2/1200/750',
      'https://picsum.photos/seed/cirkus-3/1200/750',
      'https://picsum.photos/seed/cirkus-4/1200/750',
    ],
    packages: [
      { name: 'Standard 2h', price: 340, minChildren: 20, includes: ['2h igranje', '2 animatora', 'pizza', 'GRATIS Ledo torta', 'pozivnice', 'face painting', 'foto na USB', 'poklon majica za slavljenika'] },
      { name: 'Extended 3h', price: 380, minChildren: 20, includes: ['3h igranje (pon–pet)', '2 animatora', 'pizza', 'Ledo torta', 'face painting', 'pozivnice', 'foto', 'poklon'] },
      { name: 'Extra animator', price: 410, minChildren: 20, includes: ['2h igranje', '3 animatora', 'pizza', 'Ledo torta', 'face painting', 'pozivnice', 'foto', 'poklon'] },
    ],
  },
  {
    id: 'camelot',
    slug: 'dvorac-camelot-zagreb',
    name: 'Dvorac Camelot',
    city: 'Zagreb',
    address: 'Cvijete Zuzorić 3, 10000 Zagreb (Trnje – Kruge)',
    phone: '098 138 0498',
    rating: 4.6,
    reviewCount: 70,
    pricePerChild: 16,
    ageRange: '3–12',
    ageMin: 3,
    ageMax: 12,
    maxChildren: 20,
    description: 'Tematski uređena igraonica veličine 130 m² u dvije odvojene dvorane (predškolarci/školarci + vrtićarci) s pomičnom stijenom za zakup cijelog prostora. Svaka dvorana ima air-hockey, trampolin, PlayStation, stroj za pjena party i disco opremu. Iskusni animatori s repertoarom 200+ igara.',
    amenities: ['Animatori', 'Trampolini', 'Air Hockey', 'PS4 i VR zone', 'Ekskluzivni prostor', 'Klima', 'Foto kutić'],
    coverPhoto: 'https://picsum.photos/seed/camelot-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/camelot-1/1200/750',
      'https://picsum.photos/seed/camelot-2/1200/750',
      'https://picsum.photos/seed/camelot-3/1200/750',
      'https://picsum.photos/seed/camelot-4/1200/750',
    ],
    packages: [
      { name: 'Standard 2h', price: 320, minChildren: 20, includes: ['2h igranje', '2 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'pjena party', 'face painting', 'foto na USB'] },
      { name: 'Premium 3h', price: 370, minChildren: 20, includes: ['3h igranje (pon–pet)', '2 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'pjena party', 'foto', 'poklon majica'] },
      { name: 'Ekskluzivni najam', price: 450, minChildren: 25, includes: ['Cijela igraonica (obje dvorane)', '3 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'pjena party', 'foto', 'poklon'] },
    ],
  },
  {
    id: 'zlatnidvorac',
    slug: 'zlatni-dvorac-zagreb',
    name: 'Zlatni Dvorac',
    city: 'Zagreb',
    address: 'Kučerina 74, 10000 Zagreb (Trešnjevka, kod hotela Panorama)',
    phone: '+385 1 7988 800',
    rating: 4.6,
    reviewCount: 65,
    pricePerChild: 16,
    ageRange: '3–12',
    ageMin: 3,
    ageMax: 12,
    maxChildren: 20,
    description: '200 m² prostora s dvije neovisne dvorane od 100 m² (svaka ima vlastiti ulaz, animatore i sanitarije — bez miješanja djece). Svaka dvorana opremljena bazenom s lopticama, mini toboganom, air-hockeyem, trampolinom, PlayStationom i strojem za pjena party. Iskusni animatori i face painting.',
    amenities: ['Animatori', 'Trampolini', 'Air Hockey', 'PS4 i VR zone', 'Ekskluzivni prostor', 'Face painting', 'Klima'],
    coverPhoto: 'https://picsum.photos/seed/zlatnidvorac-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/zlatnidvorac-1/1200/750',
      'https://picsum.photos/seed/zlatnidvorac-2/1200/750',
      'https://picsum.photos/seed/zlatnidvorac-3/1200/750',
      'https://picsum.photos/seed/zlatnidvorac-4/1200/750',
    ],
    packages: [
      { name: 'Standard 2h', price: 320, minChildren: 20, includes: ['2h igranje', '2 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'face painting', 'pjena party', 'foto na USB'] },
      { name: 'Extended 3h', price: 370, minChildren: 20, includes: ['3h igranje (pon–pet)', '2 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'pjena party', 'face painting', 'foto'] },
      { name: 'Cijeli najam', price: 440, minChildren: 25, includes: ['Obje dvorane', '3 animatora', 'puni catering', 'Ledo torta', 'pozivnice', 'pjena party', 'face painting', 'foto i poklon'] },
    ],
  },
  {
    id: 'zemljacuda',
    slug: 'zemlja-cuda-zagreb',
    name: 'Igraonica Zemlja Čuda',
    city: 'Zagreb',
    address: 'Murati 14, 10000 Zagreb',
    phone: '098 78 76 78',
    rating: 4.5,
    reviewCount: 45,
    pricePerChild: 12,
    ageRange: '3–12',
    ageMin: 3,
    ageMax: 12,
    maxChildren: 30,
    description: 'Igraonica orijentirana na aktivnu animaciju (a ne hranu i piće) — dvije iskusne animatorice vode djecu kroz igre i radionice. Kapacitet do 30 djece, individualan dogovor termina. Cijene paketa finaliziraju se po upitu.',
    amenities: ['Animatori', 'Kreativne radionice', 'Klima', 'Foto kutić', 'Tematske sobe'],
    coverPhoto: 'https://picsum.photos/seed/zemljacuda-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/zemljacuda-1/1200/750',
      'https://picsum.photos/seed/zemljacuda-2/1200/750',
      'https://picsum.photos/seed/zemljacuda-3/1200/750',
      'https://picsum.photos/seed/zemljacuda-4/1200/750',
    ],
    packages: [
      { name: 'Standard animacijski', price: 220, minChildren: 18, includes: ['2h aktivne animacije', '2 animatorice', 'dekoracija', 'igre i radionice', 'osvježenje'] },
      { name: 'Tematski paket', price: 270, minChildren: 18, includes: ['2h igranje', 'tematska animacija', 'kreativna radionica', 'dekoracija', 'osvježenje'] },
      { name: 'Premium do 30 djece', price: 340, minChildren: 25, includes: ['2.5h igranje', '2 animatorice', 'tematska dekoracija', 'puni catering', 'kreativna radionica'] },
    ],
  },
  {
    id: 'carobnasuma',
    slug: 'carobna-suma-zagreb',
    name: 'Čarobna Šuma',
    city: 'Zagreb',
    address: 'Braće Cvijića 15, 10000 Zagreb (Knežija)',
    phone: '098 912 8304',
    rating: 4.7,
    reviewCount: 130,
    pricePerChild: 9,
    ageRange: '1–13',
    ageMin: 1,
    ageMax: 13,
    maxChildren: 22,
    description: 'Rođendaonica i igraonica na 90 m² u Knežiji s 15+ tematskih rođendana (Space, Harry Potter, Star Wars, Frozen, Gusarski, Egipatski, Špijunski, Glamour, Mini i Maxi Basic, Baby Party). Karaoke show, Wii igre, stolni nogomet, mini disco i veseli poligon — sve pod stručnim vodstvom odgojitelja.',
    amenities: ['Animatori', 'Tematske sobe', 'Karaoke', 'Kreativne radionice', 'Foto kutić', 'Klima'],
    coverPhoto: 'https://picsum.photos/seed/carobnasuma-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/carobnasuma-1/1200/750',
      'https://picsum.photos/seed/carobnasuma-2/1200/750',
      'https://picsum.photos/seed/carobnasuma-3/1200/750',
      'https://picsum.photos/seed/carobnasuma-4/1200/750',
    ],
    packages: [
      { name: 'Mini Basic Party', price: 110, minChildren: 12, includes: ['2h igranje', 'animatori', 'karaoke i mini disco', 'dekoracija', 'osvježenje'] },
      { name: 'Maxi Basic Party', price: 160, minChildren: 18, includes: ['2h igranje', 'animatori', 'tematska dekoracija', 'karaoke', 'Wii igre', 'osvježenje'] },
      { name: 'All-inclusive tematski (Frozen, Harry Potter…)', price: 220, minChildren: 18, includes: ['2h igranje', 'tematska dekoracija', 'kostimi i rekviziti', 'animatori', 'puni catering', 'foto'] },
    ],
  },
  {
    id: 'sestinskikisobrani',
    slug: 'sestinski-kisobrani-zagreb',
    name: 'Šestinski Kišobrani',
    city: 'Zagreb',
    address: 'Kulmerska ulica 8A, 10000 Zagreb (Šestine)',
    phone: '098 958 5306',
    rating: 4.8,
    reviewCount: 70,
    pricePerChild: 9,
    ageRange: '3–14',
    ageMin: 3,
    ageMax: 14,
    maxChildren: 25,
    description: 'Zabavaonica podno Medvednice (od 2007.) s dvije etaže i 500 m² ograđenog vrta. Sportske igre na otvorenom, Nintendo Wii, supertalent, karaoke i disco rođendani. Tri ponude (Basic, Medium s grickalicama, Premium s pizzama), te poseban paket "roditelji + djeca" za 300€.',
    amenities: ['Parking', 'Animatori', 'Karaoke', 'Kreativne radionice', 'Klima', 'PS4 i VR zone', 'Roštilj terasa'],
    coverPhoto: 'https://picsum.photos/seed/sestinski-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/sestinski-1/1200/750',
      'https://picsum.photos/seed/sestinski-2/1200/750',
      'https://picsum.photos/seed/sestinski-3/1200/750',
      'https://picsum.photos/seed/sestinski-4/1200/750',
    ],
    packages: [
      { name: 'Ponuda 1 (Basic)', price: 130, minChildren: 14, includes: ['2–3h igranje', 'animatori', 'maštovito uređen prostor', 'pozivnice', 'fotografiranje', 'roditelji donose piće i grickalice'] },
      { name: 'Ponuda 2 (Medium)', price: 200, minChildren: 18, includes: ['2–3h igranje', 'animatori', 'sokovi i grickalice', 'pozivnice', 'fotografiranje', 'sportske igre na otvorenom'] },
      { name: 'Ponuda 3 (Premium)', price: 250, minChildren: 22, includes: ['2–3h igranje', 'animatori', 'pizza', 'sokovi i grickalice', 'pozivnice', 'fotografiranje', 'igre u vrtu'] },
    ],
  },
  {
    id: 'mastograd',
    slug: 'mastograd-zagreb',
    name: 'Maštograd',
    city: 'Zagreb',
    address: 'Božidarevićeva 9, 10000 Zagreb',
    phone: '098 173 5818',
    rating: 4.6,
    reviewCount: 50,
    pricePerChild: 12,
    ageRange: '1–10',
    ageMin: 1,
    ageMax: 10,
    maxChildren: 18,
    description: 'Moderna rođendaonica na 70 m² za djecu od 1 do 10 godina. Animatorice s iskustvom u radu s djecom vode zabavne, kreativne i edukativne programe. Idealno za baby i predškolske grupe — manji prostor, individualan pristup i mogućnost ekskluzivnog najma.',
    amenities: ['Animatori', 'Kreativne radionice', 'Tematske sobe', 'Ekskluzivni prostor', 'Klima', 'Foto kutić'],
    coverPhoto: 'https://picsum.photos/seed/mastograd-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/mastograd-1/1200/750',
      'https://picsum.photos/seed/mastograd-2/1200/750',
      'https://picsum.photos/seed/mastograd-3/1200/750',
      'https://picsum.photos/seed/mastograd-4/1200/750',
    ],
    packages: [
      { name: 'Baby Maštograd (1–3 god.)', price: 180, minChildren: 12, includes: ['2h igranje', 'animatorica', 'soft play', 'baby snacks i sokovi', 'dekoracija'] },
      { name: 'Standard Maštograd', price: 220, minChildren: 15, includes: ['2h igranje', 'animatorice', 'kreativna radionica', 'dekoracija', 'osvježenje', 'pozivnice'] },
      { name: 'Tematski paket', price: 280, minChildren: 15, includes: ['2.5h igranje', 'tematska dekoracija', 'kostimi', 'kreativna radionica', 'puni catering'] },
    ],
  },
  {
    id: 'klubjump',
    slug: 'klub-jump-zagreb',
    name: 'Klub JUMP',
    city: 'Zagreb',
    address: 'Ilica 118 (u dvorištu), 10000 Zagreb',
    phone: '091 445 4510',
    rating: 4.5,
    reviewCount: 40,
    pricePerChild: 11,
    ageRange: '2–12',
    ageMin: 2,
    ageMax: 12,
    maxChildren: 20,
    description: 'Prostor u srcu Zagreba (dvorište Ilice 118) za rođendane svih uzrasta. Maštovite animatorice, sigurna i čista igraonica, online rezervacija. Paket uključuje pinjatu punjenu bombonima, uokvirenu sliku slavljenika s tortom i CD sa slikama proslave.',
    amenities: ['Animatori', 'Foto kutić', 'Kreativne radionice', 'Klima', 'Javni prijevoz'],
    coverPhoto: 'https://picsum.photos/seed/jump-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/jump-1/1200/750',
      'https://picsum.photos/seed/jump-2/1200/750',
      'https://picsum.photos/seed/jump-3/1200/750',
      'https://picsum.photos/seed/jump-4/1200/750',
    ],
    packages: [
      { name: 'JUMP Basic', price: 220, minChildren: 18, includes: ['2h igranje', 'animatorice', 'sokovi', 'grickalice', 'pinjata s bombonima', 'pozivnice'] },
      { name: 'JUMP Premium', price: 270, minChildren: 18, includes: ['2h igranje', 'animatorice', 'dekoracija', 'sokovi i grickalice', 'pinjata', 'CD sa slikama', 'uokvirena slika slavljenika s tortom'] },
      { name: 'JUMP All-inclusive', price: 320, minChildren: 20, includes: ['2.5h igranje', 'tematska dekoracija', 'pizza', 'torta', 'pinjata', 'CD sa slikama', 'pozivnice'] },
    ],
  },
  {
    id: 'hrvograd',
    slug: 'hrvograd-zagreb',
    name: 'Hrvograd',
    city: 'Zagreb',
    address: 'Tratina 18, 10000 Zagreb (Gajnice)',
    phone: '098 709 007',
    rating: 4.7,
    reviewCount: 55,
    pricePerChild: 11,
    ageRange: '3–12',
    ageMin: 3,
    ageMax: 12,
    maxChildren: 20,
    description: 'Rođendaonica i igraonica u Gajnicama vođena animatorima pedagoške struke (minimum 2 po slavlju). Specijalitet: pijanistica koja svira "Sretan rođendan" za svakog slavljenika. Snimke i fotografije šalju se roditeljima na email. Nude i čuvanje/učenje s djecom radnim danom 10–16h.',
    amenities: ['Animatori', 'Kreativne radionice', 'Foto kutić', 'Klima', 'Kafić za roditelje'],
    coverPhoto: 'https://picsum.photos/seed/hrvograd-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/hrvograd-1/1200/750',
      'https://picsum.photos/seed/hrvograd-2/1200/750',
      'https://picsum.photos/seed/hrvograd-3/1200/750',
      'https://picsum.photos/seed/hrvograd-4/1200/750',
    ],
    packages: [
      { name: 'Hrvograd Basic', price: 200, minChildren: 18, includes: ['2h igranje', '2 animatora pedagoške struke', 'pijanistica', 'sokovi i grickalice', 'pozivnice'] },
      { name: 'Hrvograd Standard', price: 250, minChildren: 18, includes: ['2h igranje', '2 animatora', 'pijanistica', 'kreativna radionica', 'dekoracija', 'foto i video na email'] },
      { name: 'Hrvograd Premium', price: 320, minChildren: 20, includes: ['3h igranje', '2 animatora', 'pijanistica', 'pizza', 'torta', 'kreativna radionica', 'foto/video'] },
    ],
  },
  {
    id: 'jungleplay1',
    slug: 'jungle-play-1-zagreb',
    name: 'Jungle Play 1',
    city: 'Zagreb',
    address: 'Vajdin vijenac 2, 10000 Zagreb (Dugave)',
    phone: '+385 1 6692 357',
    rating: 4.6,
    reviewCount: 95,
    pricePerChild: 17,
    ageRange: '3–12',
    ageMin: 3,
    ageMax: 12,
    maxChildren: 20,
    description: '165 m² igraonice u Dugavama u dvije tematski uređene dvorane (predškolarci/školarci + vrtićarci) sa simulatorom vožnje, air-hockeyem, trampolinima i strojem za pjena party. Vlastito parkiralište i dječje igralište. GRATIS Ledo Medo torta uključena u svaki paket.',
    amenities: ['Parking', 'Animatori', 'Trampolini', 'Air Hockey', 'Foto kutić', 'Ekskluzivni prostor', 'Klima'],
    coverPhoto: 'https://picsum.photos/seed/jungleplay1-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/jungleplay1-1/1200/750',
      'https://picsum.photos/seed/jungleplay1-2/1200/750',
      'https://picsum.photos/seed/jungleplay1-3/1200/750',
      'https://picsum.photos/seed/jungleplay1-4/1200/750',
    ],
    packages: [
      { name: 'Standard 2h', price: 340, minChildren: 20, includes: ['2h igranje', '2 animatora', 'pizza', 'GRATIS Ledo Medo torta', 'pozivnice', 'face painting', 'foto na USB', 'poklon majica'] },
      { name: 'Extended 3h', price: 380, minChildren: 20, includes: ['3h igranje (pon–pet)', '2 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'pjena party', 'face painting', 'foto'] },
      { name: 'Extra animator', price: 410, minChildren: 20, includes: ['2h igranje', '3 animatora', 'pizza', 'Ledo torta', 'pozivnice', 'pjena party', 'face painting', 'foto'] },
    ],
  },
  {
    id: 'aqua',
    slug: 'aqua-zagreb',
    name: 'Aqua',
    city: 'Zagreb',
    address: 'Hrvatskog proljeća 32, 10040 Zagreb',
    phone: '098 135 4046',
    rating: 4.7,
    reviewCount: 90,
    pricePerChild: 10,
    ageRange: '3–12',
    ageMin: 3,
    ageMax: 12,
    maxChildren: 25,
    description: 'Tematski moderno uređena rođendaonica s 10+ godina iskustva. LED plesna pozornica, poligon/labirint s toboganom, stolni hokej i nogomet. Tri jasna paketa (Basic, Play, Best) — sve s pizzom, Ledo tortom, slatkišima i sokovima. Tematske rođendane biraš ti (BEST paket).',
    amenities: ['Animatori', 'Labirinti', 'Tematske sobe', 'Foto kutić', 'Torta po narudžbi', 'Klima'],
    coverPhoto: 'https://picsum.photos/seed/aqua-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/aqua-1/1200/750',
      'https://picsum.photos/seed/aqua-2/1200/750',
      'https://picsum.photos/seed/aqua-3/1200/750',
      'https://picsum.photos/seed/aqua-4/1200/750',
    ],
    packages: [
      { name: 'Aqua Basic', price: 200, minChildren: 20, includes: ['2h igranje', 'profesionalni animatori', 'LED plesna pozornica', 'labirint s toboganom', 'pizza', 'Ledo torta', 'sokovi i slatkiši', 'foto na WhatsApp'] },
      { name: 'Aqua Play', price: 220, minChildren: 20, includes: ['Sve iz Basic', 'pjena party', 'poklončić za slavljenika', '2 razvijene fotografije'] },
      { name: 'Aqua Best (tematski)', price: 250, minChildren: 20, includes: ['Sve iz Play', 'tematski rođendan po izboru', 'vatromet i dječji šampanjac', 'makeup kutić', 'poklončići za sve goste'] },
    ],
  },
  {
    id: 'pingo',
    slug: 'pingo-dubrava-zagreb',
    name: 'Rođendaonica Pingo',
    city: 'Zagreb',
    address: 'Koledinečka 4, 10000 Zagreb (Dubrava, zgrada Placa, 1. kat)',
    phone: '095 816 1134',
    rating: 4.5,
    reviewCount: 35,
    pricePerChild: 10,
    ageRange: '2–15',
    ageMin: 2,
    ageMax: 15,
    maxChildren: 30,
    description: 'Rođendaonica preko puta Ofertisime u Dubravi, na 1. katu zgrade Placa. Veliki raspon dobi (2–15 godina), kapacitet do 30 djece. Online rezervacija s odabirom dobi i datuma. Druga lokacija u Anini 20b. Detalji paketa po upitu.',
    amenities: ['Animatori', 'Tematske sobe', 'Foto kutić', 'Klima', 'Javni prijevoz'],
    coverPhoto: 'https://picsum.photos/seed/pingo-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/pingo-1/1200/750',
      'https://picsum.photos/seed/pingo-2/1200/750',
      'https://picsum.photos/seed/pingo-3/1200/750',
      'https://picsum.photos/seed/pingo-4/1200/750',
    ],
    packages: [
      { name: 'Pingo Standard', price: 200, minChildren: 20, includes: ['2h igranje', 'animatori', 'dekoracija', 'osvježenje', 'pozivnice'] },
      { name: 'Pingo Tematski', price: 240, minChildren: 20, includes: ['2h igranje', 'tematska dekoracija', 'animatori', 'osvježenje', 'pozivnice'] },
      { name: 'Pingo Premium', price: 290, minChildren: 25, includes: ['2.5h igranje', 'tematska dekoracija', 'animatori', 'pizza', 'torta', 'foto'] },
    ],
  },
  {
    id: 'tigric',
    slug: 'tigric-zagreb',
    name: 'Sportska rođendaonica Tigrić',
    city: 'Zagreb',
    address: 'Kamenarka 2, 10010 Zagreb (Dugave, Tigar Centar)',
    phone: '091 536 1951',
    rating: 4.7,
    reviewCount: 60,
    pricePerChild: 12,
    ageRange: '4–14',
    ageMin: 4,
    ageMax: 14,
    maxChildren: 25,
    description: 'Sportski rođendani u dvorani Tigar Centar — 2–3h aktivnog programa s profesionalnim trenerima i sportskim animatorima. Natjecanja u nogometu, rukometu, graničaru, povlačenju konopca i poligonima. Probni treninzi taekwondoa, disco/karaoke i LED rasvjeta. Snimanje video materijala uključeno.',
    amenities: ['Parking', 'Animatori', 'Karaoke', 'Foto kutić', 'Klima', 'Trampolini'],
    coverPhoto: 'https://picsum.photos/seed/tigric-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/tigric-1/1200/750',
      'https://picsum.photos/seed/tigric-2/1200/750',
      'https://picsum.photos/seed/tigric-3/1200/750',
      'https://picsum.photos/seed/tigric-4/1200/750',
    ],
    packages: [
      { name: 'Sportski Basic', price: 220, minChildren: 18, includes: ['2h aktivnog programa', 'sportski treneri', 'pizza', 'Ledo Medo torta', 'sokovi i grickalice', 'poklon majica za slavljenika'] },
      { name: 'Sportski Standard', price: 280, minChildren: 20, includes: ['2.5h aktivnog programa', 'sportski treneri i animatori', 'pizza', 'Ledo torta', 'disco/karaoke', 'foto i video'] },
      { name: 'Tigrić Premium 3h', price: 340, minChildren: 22, includes: ['3h programa', 'probni trening taekwondoa', 'pizza', 'Ledo torta', 'dječji šampanjac', 'pozivnice s kuponima', 'foto i video'] },
    ],
  },
  {
    id: 'ncstenjevec',
    slug: 'nc-stenjevec-zagreb',
    name: 'NC Stenjevec',
    city: 'Zagreb',
    address: 'Hrvatskih branitelja 10, 10000 Zagreb (Poslovna zona Zapad)',
    phone: '098 163 4894',
    rating: 4.6,
    reviewCount: 80,
    pricePerChild: 13,
    ageRange: '4–14',
    ageMin: 4,
    ageMax: 14,
    maxChildren: 25,
    description: 'Sportski centar s 1.500 m² nogometnih terena s umjetnom travom, grijana dvorana, slavljenički ukrašena rođendaonica i caffe bar 200 m² s ljetnom terasom. Napuhani dvorci, mini-tenis, boćanje, mini-nogomet i animatori. Čuvani parking. Termini vikendom u tri slota.',
    amenities: ['Parking', 'Restoran', 'Animatori', 'Roštilj terasa', 'Foto kutić', 'Klima', 'Video nadzor'],
    coverPhoto: 'https://picsum.photos/seed/ncstenjevec-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/ncstenjevec-1/1200/750',
      'https://picsum.photos/seed/ncstenjevec-2/1200/750',
      'https://picsum.photos/seed/ncstenjevec-3/1200/750',
      'https://picsum.photos/seed/ncstenjevec-4/1200/750',
    ],
    packages: [
      { name: 'NC Stenjevec Basic 3h', price: 280, minChildren: 18, includes: ['3h proslava', 'nogometni teren 1.500 m²', 'animatori', 'grickalice i sokovi', 'torta po želji', 'fotografije'] },
      { name: 'NC Stenjevec s napuhancem', price: 340, minChildren: 20, includes: ['3h proslava', 'napuhani dvorac/tobogan', 'animatori', 'caffe bar usluga', 'pizza', 'torta', 'foto'] },
      { name: 'Sportski multi-paket', price: 390, minChildren: 22, includes: ['3h proslava', 'mini-nogomet, mini-tenis, boćanje, plesanje', 'animatori', 'puni catering', 'tematska dekoracija', 'foto'] },
    ],
  },
  {
    id: 'ncsalata',
    slug: 'nc-salata-zagreb',
    name: 'NC Šalata',
    city: 'Zagreb',
    address: 'Avenija Dubrovnik 15, Velesajam paviljon 1, 10010 Zagreb',
    phone: '+385 98 276 444',
    rating: 4.6,
    reviewCount: 95,
    pricePerChild: 14,
    ageRange: '6–14',
    ageMin: 6,
    ageMax: 14,
    maxChildren: 25,
    description: '15+ godina iskustva u nogometnim rođendanima. Dva animatora — jedan vodi nogometni turnir (bira ekipe i sudi), drugi organizira igre za djecu koja ne žele nogomet. Tematska dekoracija s grbom kluba, dvorac na napuhavanje i balon kup kao dodaci. Vikend termini 11–13, 15–17 i 17:30–19:30.',
    amenities: ['Parking', 'Animatori', 'Torta po narudžbi', 'Foto kutić', 'Klima', 'Ugostiteljstvo'],
    coverPhoto: 'https://picsum.photos/seed/ncsalata-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/ncsalata-1/1200/750',
      'https://picsum.photos/seed/ncsalata-2/1200/750',
      'https://picsum.photos/seed/ncsalata-3/1200/750',
      'https://picsum.photos/seed/ncsalata-4/1200/750',
    ],
    packages: [
      { name: 'Basic Rođendan', price: 270, minChildren: 20, includes: ['Nogometni teren', '2 animatora', 'Ledo torta', 'grickalice, keksi i sokovi', 'digitalne pozivnice'] },
      { name: 'Tematski Rođendan', price: 390, minChildren: 20, includes: ['Sve iz Basic', 'tematska dekoracija s grbom kluba', 'pizze (3 kom)', 'tematske čokolade'] },
      { name: 'Premium s napuhancem', price: 460, minChildren: 22, includes: ['Sve iz Basic', 'dvorac na napuhavanje', 'dodatni animator', 'pizze', 'balon kup', 'tematska dekoracija'] },
    ],
  },
  {
    id: 'olympionic',
    slug: 'olympionic-club-zagreb',
    name: 'Olympionic Club',
    city: 'Zagreb',
    address: '1. Pile 21, 10000 Zagreb (Kruge)',
    phone: '099 234 3442',
    rating: 4.5,
    reviewCount: 50,
    pricePerChild: 13,
    ageRange: '4–12',
    ageMin: 4,
    ageMax: 12,
    maxChildren: 22,
    description: 'Klub zabave i rekreacije s ~200 m² i tematskim sobama. Sportska dvorana, diskoteka, PlayStation 3, Xbox 360, Nintendo Wii, Playmobili, Brio pruge i Lego Duplo. Proslave 3h s igrama u sportskoj dvorani, hranom, plesanjem u disco i animacijom. Nudi i sportsku školu i ritmiku.',
    amenities: ['Animatori', 'Tematske sobe', 'PS4 i VR zone', 'Klima', 'Kreativne radionice', 'Foto kutić'],
    coverPhoto: 'https://picsum.photos/seed/olympionic-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/olympionic-1/1200/750',
      'https://picsum.photos/seed/olympionic-2/1200/750',
      'https://picsum.photos/seed/olympionic-3/1200/750',
      'https://picsum.photos/seed/olympionic-4/1200/750',
    ],
    packages: [
      { name: 'Olympionic Standard 3h', price: 260, minChildren: 18, includes: ['3h igranje', 'sportska dvorana i diskoteka', 'animatori', 'grickalice, pizze i torta', 'plesni dio'] },
      { name: 'Olympionic Sport', price: 310, minChildren: 20, includes: ['3h igranje', 'sportska škola program', 'PlayStation/Xbox/Wii zona', 'animatori', 'puni catering'] },
      { name: 'Olympionic Premium', price: 360, minChildren: 22, includes: ['3h igranje', 'tematske sobe (Lego Duplo, Brio, Playmobil)', 'sportska dvorana', 'puni catering', 'foto'] },
    ],
  },
  {
    id: 'winnerkids',
    slug: 'winner-kids-zagreb',
    name: 'Winner Kids',
    city: 'Zagreb',
    address: 'Slavenskoga 1/3, 10000 Zagreb (Shopping centar Prečko, 3. kat)',
    phone: '091 570 8709',
    rating: 4.5,
    reviewCount: 75,
    pricePerChild: 14,
    ageRange: '3–12',
    ageMin: 3,
    ageMax: 12,
    maxChildren: 25,
    description: '700 m² rođendaonice u Sportskom centru Winner (Shopping Prečko, 3. kat) — napuhanci, bazen s lopticama, mini-tobogan, košarkaški koševi i sportski rekviziti. Sve aktivnosti pod stručnim vodstvom kineziologa. Roditelji imaju prostor za promatranje. Pun epidemiološki standard.',
    amenities: ['Parking', 'Animatori', 'Trampolini', 'Klima', 'Kafić za roditelje', 'Video nadzor'],
    coverPhoto: 'https://picsum.photos/seed/winnerkids-cover/1200/750',
    photos: [
      'https://picsum.photos/seed/winnerkids-1/1200/750',
      'https://picsum.photos/seed/winnerkids-2/1200/750',
      'https://picsum.photos/seed/winnerkids-3/1200/750',
      'https://picsum.photos/seed/winnerkids-4/1200/750',
    ],
    packages: [
      { name: 'Winner Kids Basic', price: 280, minChildren: 20, includes: ['2h igranje', 'kineziolog/animator', 'napuhanci i košarkaški koševi', 'sokovi i grickalice', 'pozivnice'] },
      { name: 'Winner Kids Sport', price: 340, minChildren: 20, includes: ['2.5h igranje', 'kineziolozi', 'sportski poligon i mini-tobogan', 'pizza', 'torta', 'foto'] },
      { name: 'Winner Kids All-inclusive', price: 400, minChildren: 22, includes: ['2.5h igranje', 'kineziolog + animator', 'puni sportski program', 'puni catering', 'tematska dekoracija', 'foto'] },
    ],
  },
]

export const testimonials: Testimonial[] = [
  {
    quote: 'Pozivnica je bila gotova dok sam čekala kavu. Kad su je roditelji dobili na WhatsApp, svi su komentirali koliko lijepo izgleda.',
    name: 'Ivana M.',
    childAge: 'Lara, 5 godina',
    city: 'Zagreb',
    monogram: 'IM',
  },
  {
    quote: 'Print verziju smo ubacili u ormariće u vrtiću, a ista pozivnica je otišla i linkom. Nema zbunjivanja, nema duplih info.',
    name: 'Ana K.',
    childAge: 'Matej, 4 godine',
    city: 'Split',
    monogram: 'AK',
  },
  {
    quote: 'Tražila sam igraonicu koja prima djecu od 3 godine i da ima parking. Našla za 5 minuta umjesto da zovem po cijelom gradu.',
    name: 'Marina P.',
    childAge: 'Noa, 3 godine',
    city: 'Rijeka',
    monogram: 'MP',
  },
]

export const faqItems: FAQItem[] = [
  {
    question: 'Je li pozivnica besplatna?',
    answer: 'Da, osnovna digitalna pozivnica je potpuno besplatna. Možeš je kreirati, podijeliti linkom i pratiti tko dolazi bez ikakve naknade. Premium teme i napredne opcije dostupne su uz simboličnu nadoplatu.',
  },
  {
    question: 'Kako gosti potvrđuju dolazak?',
    answer: 'Na digitalnoj pozivnici klikom na gumb "Dolazimo" ili "Ne možemo". Na printanoj pozivnici skeniraju QR kod koji ih vodi na istu stranicu za potvrdu. Sve potvrde vidiš na jednom mjestu u svom dashboardu.',
  },
  {
    question: 'Mogu li printati pozivnicu?',
    answer: 'Apsolutno. Svaka pozivnica koju napraviš automatski ima i PDF verziju optimiziranu za print. Samo klikni "Preuzmi PDF", isprintaj kod kuće ili u kopirnici, i podijeli u vrtiću.',
  },
  {
    question: 'Kako se plaća igraonica?',
    answer: 'Plaćanje se dogovara direktno s igraonicom. VidimoSe.hr ti pomaže pronaći i usporediti opcije, ali rezervacija i plaćanje idu kroz igraonicu. Radimo na integraciji online rezervacija.',
  },
  {
    question: 'Mogu li dodati vlastitu igraonicu?',
    answer: 'Da! Ako imaš igraonicu i želiš biti vidljiv roditeljima, javi nam se putem kontakt forme. Dodavanje je besplatno za sve igraonice u Hrvatskoj.',
  },
  {
    question: 'Radi li u cijeloj Hrvatskoj?',
    answer: 'Pozivnice rade svugdje — nema ograničenja po lokaciji. Baza igraonica trenutno pokriva veće gradove (Zagreb, Split, Rijeka, Osijek, Zadar), a aktivno dodajemo nove svaki tjedan.',
  },
]
